name: Build and Test iOS

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - name: Install Ruby dependencies via Bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install
      # - name: Install Fastlane
      #   run: |
      #     gem install fastlane
      - name: Install Swift Packages
        run: |
          xcodebuild -resolvePackageDependencies -project iosMovieapp.xcodeproj
      - name: Run unit tests
        run: bundle exec fastlane run_unit_tests